FROM debian:buster-slim
LABEL maintainer="pmatos@linki.tools"
LABEL description="Debian Buster Slim image with LLVM Scan Build compiled with Z3 support for static analysis"

COPY install-llvmsa.sh .

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y git gcc cmake wget unzip g++ python libxml2-dev ninja-build python ruby python-pip && \
	./install-llvmsa.sh && \
	apt-get clean

CMD ["bash"]

